package com.gurukul.teachers.entity;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Teacher-facing product features planned for the Gurukul platform")
public enum TeacherFeature {
	CLASS_TIMETABLE,
	SMART_REMINDERS,
	ATTENDANCE_MARKING,
	TEACHER_ATTENDANCE_LEAVE,
	ASSIGNMENT_CREATION,
	HOMEWORK_REVIEW,
	GRADEBOOK,
	STUDENT_PERFORMANCE_INSIGHTS,
	AI_CLASS_SUMMARIES,
	AI_NOTES_GENERATOR,
	AI_QUIZ_GENERATOR,
	AI_QUESTION_PAPER_GENERATOR,
	AI_LESSON_PLANNER,
	AI_DOUBT_MODERATION,
	PARENT_COMMUNICATION,
	RESOURCE_LIBRARY,
	QUIZ_TEST_SCHEDULER,
	DISCUSSION_MODERATION,
	DIGITAL_CERTIFICATES,
	WELLNESS_ESCALATION_VIEW,
	OFFLINE_RESOURCE_SHARING,
	REGIONAL_LANGUAGE_SUPPORT
}
