package com.gurukul.idcards.service;

import com.gurukul.common.pdf.PdfRenderService;
import com.gurukul.idcards.dto.IdCardDtos.IdCardResponse;
import com.gurukul.idcards.entity.IdCardOwnerType;
import com.gurukul.idcards.service.IdCardService.PrintData;
import com.gurukul.idcards.service.IdCardService.PrintEntry;
import com.gurukul.schools.entity.School;
import com.gurukul.schools.service.SchoolLogoService;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.rendering.PDFRenderer;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Validation, layout and real renders of the ID-card template. Run with -Dpdf.preview=true to also
 * write the PDFs and a PNG of each first page to target/pdf-preview/ for eyeballing.
 */
class IdCardUnitTest {

	private static final float MM = 72f / 25.4f;

	private final IdCardCodec codec = new IdCardCodec("", "dev-only-insecure-secret-change-me-before-prod-32bytes!");
	private final ProfilePhotoService photoService = mock(ProfilePhotoService.class);
	private final SchoolLogoService logoService = mock(SchoolLogoService.class);
	private final IdCardPdfService pdfService = new IdCardPdfService(
			null, new PdfRenderService(), logoService, photoService, new IdCardQrService());

	@Test
	void normalisesBloodGroupsAndRejectsNonsense() {
		assertThat(IdCardService.normaliseBloodGroup("b+")).isEqualTo("B+");
		assertThat(IdCardService.normaliseBloodGroup(" ab - ")).isEqualTo("AB-");
		assertThat(IdCardService.normaliseBloodGroup("O +ve")).isEqualTo("O+");
		assertThat(IdCardService.normaliseBloodGroup("A negative")).isEqualTo("A-");
		assertThat(IdCardService.normaliseBloodGroup("  ")).isNull();
		assertThat(IdCardService.normaliseBloodGroup(null)).isNull();
		assertThatThrownBy(() -> IdCardService.normaliseBloodGroup("C+")).isInstanceOf(IllegalArgumentException.class);
		assertThatThrownBy(() -> IdCardService.normaliseBloodGroup("AB")).isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void normalisesPhonesAndRejectsNonsense() {
		assertThat(IdCardService.normalisePhone("+91 98765-43210")).isEqualTo("+919876543210");
		assertThat(IdCardService.normalisePhone("(0731) 2345678")).isEqualTo("07312345678");
		assertThat(IdCardService.normalisePhone("")).isNull();
		assertThatThrownBy(() -> IdCardService.normalisePhone("12345")).isInstanceOf(IllegalArgumentException.class);
		assertThatThrownBy(() -> IdCardService.normalisePhone("98765abcde")).isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void sortsRollNumbersNaturally() {
		List<String> rolls = new ArrayList<>(List.of("10", "2", "1", "A-3", "A-12"));
		rolls.sort(IdCardService::naturalCompare);
		assertThat(rolls).containsExactly("1", "2", "10", "A-3", "A-12");
	}

	@Test
	void laysOutTenCardsPerPageInRowsOfTwo() {
		var pages = IdCardPdfService.layout(IntStream.range(0, 23).boxed().toList());
		assertThat(pages).hasSize(3);
		assertThat(pages.get(0)).hasSize(5).allSatisfy(row -> assertThat(row).hasSize(2));
		assertThat(pages.get(2)).hasSize(2);
		assertThat(pages.get(2).get(1)).containsExactly(22);
	}

	@Test
	void rendersASingleCardAtCr80SizeWithAHindiNameAndPlaceholders() throws Exception {
		when(logoService.fetchLogo(any())).thenReturn(Optional.empty());
		when(photoService.fetch(any())).thenReturn(Optional.empty());

		PrintEntry entry = student("प्रिया शर्मा", "7", null, null);
		byte[] pdf = pdfService.render(data(List.of(entry)), false);

		try (PDDocument document = Loader.loadPDF(pdf)) {
			assertThat(document.getNumberOfPages()).isEqualTo(1);
			PDRectangle box = document.getPage(0).getMediaBox();
			assertThat(box.getWidth()).isCloseTo(85.6f * MM, org.assertj.core.data.Offset.offset(1f));
			assertThat(box.getHeight()).isCloseTo(54f * MM, org.assertj.core.data.Offset.offset(1f));
			String text = new PDFTextStripper().getText(document);
			assertThat(text).contains("STUDENT", "Grade 5 - A", "Roll No", "Parent Ph", "Generated by Gurukul", "Valid 2026-27");
			// The printed QR really scans back to the signed code.
			BufferedImage page = new PDFRenderer(document).renderImageWithDPI(0, 300);
			assertThat(decodeQr(page)).isEqualTo(entry.card().getQrCode());
			preview("id-card-single", pdf, document);
		}
	}

	@Test
	void rendersAnA4SheetWithAPhotoAndStaffCards() throws Exception {
		when(logoService.fetchLogo(any())).thenReturn(Optional.empty());
		when(photoService.fetch("photo-key")).thenReturn(Optional.of(new ProfilePhotoService.PhotoImage(samplePhoto(), "image/png")));
		when(photoService.fetch(null)).thenReturn(Optional.empty());

		List<PrintEntry> entries = new ArrayList<>();
		entries.add(student("Aarav Kumar", "1", "B+", "photo-key"));
		for (int i = 2; i <= 11; i++) {
			entries.add(student("Student " + i, String.valueOf(i), i % 2 == 0 ? "O+" : null, null));
		}
		entries.add(staff("Meena Verma", "Mathematics Teacher"));
		byte[] pdf = pdfService.render(data(entries), true);

		try (PDDocument document = Loader.loadPDF(pdf)) {
			assertThat(document.getNumberOfPages()).isEqualTo(2);
			PDRectangle box = document.getPage(0).getMediaBox();
			assertThat(box.getWidth()).isCloseTo(PDRectangle.A4.getWidth(), org.assertj.core.data.Offset.offset(1f));
			PDFTextStripper stripper = new PDFTextStripper();
			stripper.setStartPage(1);
			stripper.setEndPage(1);
			String first = stripper.getText(document);
			assertThat(first).contains("Aarav Kumar", "Student 10").doesNotContain("Student 11");
			stripper.setStartPage(2);
			stripper.setEndPage(2);
			assertThat(stripper.getText(document)).contains("Student 11", "Meena Verma", "STAFF", "Mathematics Teacher");
			preview("id-card-sheet", pdf, document);
		}
	}

	@Test
	void downscalesLargePhotosAndIgnoresUndecodableOnes() throws Exception {
		BufferedImage big = new BufferedImage(1200, 1600, BufferedImage.TYPE_INT_RGB);
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		ImageIO.write(big, "png", out);
		String uri = IdCardPdfService.downscale(out.toByteArray());
		assertThat(uri).startsWith("data:image/jpeg;base64,");
		BufferedImage scaled = ImageIO.read(new java.io.ByteArrayInputStream(
				java.util.Base64.getDecoder().decode(uri.substring(uri.indexOf(',') + 1))));
		assertThat(scaled.getWidth()).isEqualTo(300);
		assertThat(scaled.getHeight()).isEqualTo(400);
		assertThat(IdCardPdfService.downscale(new byte[] {1, 2, 3})).isNull();
	}

	// ---------------------------------------------------------------- fixtures

	private PrintData data(List<PrintEntry> entries) {
		School school = new School();
		school.setId(UUID.randomUUID());
		school.setName("श्री विद्या निकेतन");
		school.setAddress("12 MG Road");
		school.setCity("Indore");
		school.setState("MP");
		school.setContactPhone("0731-2345678");
		return new PrintData(school, entries, "test");
	}

	private PrintEntry student(String name, String roll, String bloodGroup, String photoKey) {
		UUID id = UUID.randomUUID();
		IdCardResponse card = IdCardResponse.builder()
				.ownerType(IdCardOwnerType.STUDENT).ownerId(id).name(name)
				.classSectionLabel("Grade 5 - A").rollNumber(roll).academicYear("2026-27")
				.parentName("सुनीता शर्मा").bloodGroup(bloodGroup).cardPhone("9876543210")
				.qrCode(codec.encode(IdCardOwnerType.STUDENT, id, UUID.randomUUID()))
				.build();
		return new PrintEntry(card, photoKey);
	}

	private PrintEntry staff(String name, String designation) {
		UUID id = UUID.randomUUID();
		IdCardResponse card = IdCardResponse.builder()
				.ownerType(IdCardOwnerType.EMPLOYEE).ownerId(id).name(name).designation(designation)
				.bloodGroup("A+").emergencyPhone("+919812345678").cardPhone("+919812345678").emergencyContactName("Rakesh Verma")
				.qrCode(codec.encode(IdCardOwnerType.EMPLOYEE, id, UUID.randomUUID()))
				.build();
		return new PrintEntry(card, null);
	}

	private static String decodeQr(BufferedImage image) throws Exception {
		int[] pixels = image.getRGB(0, 0, image.getWidth(), image.getHeight(), null, 0, image.getWidth());
		var source = new com.google.zxing.RGBLuminanceSource(image.getWidth(), image.getHeight(), pixels);
		var bitmap = new com.google.zxing.BinaryBitmap(new com.google.zxing.common.HybridBinarizer(source));
		return new com.google.zxing.qrcode.QRCodeReader()
				.decode(bitmap, java.util.Map.of(com.google.zxing.DecodeHintType.TRY_HARDER, Boolean.TRUE))
				.getText();
	}

	private static byte[] samplePhoto() throws Exception {
		BufferedImage image = new BufferedImage(600, 800, BufferedImage.TYPE_INT_RGB);
		var g = image.createGraphics();
		g.setColor(new java.awt.Color(0x3B82F6));
		g.fillRect(0, 0, 600, 800);
		g.setColor(new java.awt.Color(0xFDE68A));
		g.fillOval(180, 150, 240, 240);
		g.fillRoundRect(100, 420, 400, 400, 200, 200);
		g.dispose();
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		ImageIO.write(image, "png", out);
		return out.toByteArray();
	}

	private static void preview(String name, byte[] pdf, PDDocument document) throws Exception {
		if (!Boolean.getBoolean("pdf.preview")) {
			return;
		}
		File dir = new File("target/pdf-preview");
		dir.mkdirs();
		java.nio.file.Files.write(new File(dir, name + ".pdf").toPath(), pdf);
		ImageIO.write(new PDFRenderer(document).renderImageWithDPI(0, 300), "png", new File(dir, name + ".png"));
	}

}
