-- Replaces the V32 placeholder practice questions ("Practice: Grade X Subject Question N",
-- same generic 4 options every time) with real, curriculum-relevant MCQs per grade (6-12) and
-- subject, aligned to the CBSE/NCERT syllabus JNV schools follow. Kept at 5 questions per
-- (grade, subject) - the minimum ArenaService.createChallenge() requires per class+subject pool.
DELETE FROM quiz_question
WHERE school_id = '99999999-9999-9999-9999-999999999999' AND question_text LIKE 'Practice: %';

CREATE TEMP TABLE t_curriculum_teacher AS
SELECT id FROM employee
WHERE school_id = '99999999-9999-9999-9999-999999999999'
ORDER BY id LIMIT 1;

INSERT INTO quiz_question (
    id, school_id, subject_id, class_name, question_text,
    option_a, option_b, option_c, option_d, correct_option,
    created_by_teacher_id, created_at, updated_at
)
SELECT
    gen_random_uuid(), '99999999-9999-9999-9999-999999999999', sub.id, v.class_name, v.question_text,
    v.option_a, v.option_b, v.option_c, v.option_d, v.correct_option,
    (SELECT id FROM t_curriculum_teacher), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (VALUES
-- ===================== MATHEMATICS =====================
('MAT','Grade 6','What is the LCM of 4 and 6?','10','12','24','8','B'),
('MAT','Grade 6','Which of these is a prime number?','9','15','17','21','C'),
('MAT','Grade 6','3/4 written as a decimal is?','0.34','0.75','0.43','1.33','B'),
('MAT','Grade 6','What is the perimeter of a square with side 5 cm?','10 cm','15 cm','20 cm','25 cm','C'),
('MAT','Grade 6','What is the successor of 999?','998','1000','1001','900','B'),
('MAT','Grade 7','Solve: 2x + 3 = 11. What is x?','3','4','5','6','B'),
('MAT','Grade 7','The sum of angles in a triangle is?','90 degrees','180 degrees','270 degrees','360 degrees','B'),
('MAT','Grade 7','Simple interest on Rs 1000 at 5% per year for 2 years is?','Rs 50','Rs 100','Rs 150','Rs 200','B'),
('MAT','Grade 7','Which of these is a rational number?','Square root of 2','Pi','3/4','Square root of 3','C'),
('MAT','Grade 7','The value of (-3) x (-4) is?','-12','12','7','-7','B'),
('MAT','Grade 8','Solve for x: 3x - 7 = 14','5','6','7','8','C'),
('MAT','Grade 8','A cube has how many faces?','4','6','8','12','B'),
('MAT','Grade 8','What is the square root of 144?','11','12','13','14','B'),
('MAT','Grade 8','Compound interest is calculated on?','Principal only','Principal plus accrued interest','Interest only','None of these','B'),
('MAT','Grade 8','Which of these is an irrational number?','0.5','2/3','Square root of 5','7','C'),
('MAT','Grade 9','What is the value of x in x squared = 81?','+/- 7','+/- 8','+/- 9','+/- 10','C'),
('MAT','Grade 9','Which of these is a linear equation in two variables?','x squared + y = 5','x + y = 5','xy = 5','x squared + y squared = 5','B'),
('MAT','Grade 9','The distance formula between two points is derived from?','Pythagoras theorem','Thales theorem','Euclid postulate','None of these','A'),
('MAT','Grade 9','In a triangle, an exterior angle equals?','Sum of the two opposite interior angles','180 minus the interior angle','Half the interior angle','None of these','A'),
('MAT','Grade 9','The number pi is?','Rational','Irrational','An integer','A natural number','B'),
('MAT','Grade 10','The quadratic formula solves equations of the form?','ax + b = 0','ax squared + bx + c = 0','a x cubed = 0','None of these','B'),
('MAT','Grade 10','If sin(theta) = 1, then theta equals?','0 degrees','30 degrees','90 degrees','45 degrees','C'),
('MAT','Grade 10','The nth term of an arithmetic progression is given by?','a + (n-1)d','a times n to the power d','a - nd','a / n','A'),
('MAT','Grade 10','The probability of an impossible event is?','1','0.5','0','-1','C'),
('MAT','Grade 10','The HCF of two co-prime numbers is?','0','1','Their product','Their sum','B'),
('MAT','Grade 11','The value of sin(90 - theta) equals?','sin(theta)','cos(theta)','tan(theta)','-sin(theta)','B'),
('MAT','Grade 11','The set of natural numbers is denoted by?','Z','Q','N','R','C'),
('MAT','Grade 11','The derivative of x squared is?','x','2x','x squared','2','B'),
('MAT','Grade 11','In the binomial expansion of (a+b) to the power n, the number of terms is?','n','n - 1','n + 1','2n','C'),
('MAT','Grade 11','The value of log(1) in any base is?','1','0','Undefined','-1','B'),
('MAT','Grade 12','The derivative of e to the power x is?','e to the power x','x times e to the power (x-1)','ln(x)','1','A'),
('MAT','Grade 12','The integral of 1/x dx is?','x squared / 2','ln|x| + C','1/x squared','e to the power x','B'),
('MAT','Grade 12','A matrix with an equal number of rows and columns is called?','Rectangular','Square','Diagonal','Null','B'),
('MAT','Grade 12','The probability of a certain event is?','0','0.5','1','-1','C'),
('MAT','Grade 12','If A and B are independent events, P(A intersection B) equals?','P(A) + P(B)','P(A) times P(B)','P(A) - P(B)','P(A) / P(B)','B'),
-- ===================== SCIENCE =====================
('SCI','Grade 6','Which part of the plant makes food?','Root','Stem','Leaf','Flower','C'),
('SCI','Grade 6','The process of water changing to vapour is called?','Condensation','Evaporation','Freezing','Melting','B'),
('SCI','Grade 6','Which of these is a natural source of light?','Moon','Sun','Mirror','Book','B'),
('SCI','Grade 6','Which gas do plants release during photosynthesis?','Carbon dioxide','Oxygen','Nitrogen','Hydrogen','B'),
('SCI','Grade 6','A magnet attracts which of these materials?','Wood','Plastic','Iron','Paper','C'),
('SCI','Grade 7','Which organ pumps blood in the human body?','Lungs','Heart','Kidney','Liver','B'),
('SCI','Grade 7','The process by which plants lose water through their leaves is called?','Respiration','Transpiration','Photosynthesis','Absorption','B'),
('SCI','Grade 7','Which of these is a non-metal?','Iron','Copper','Sulphur','Zinc','C'),
('SCI','Grade 7','Acid rain is mainly caused by?','Carbon dioxide','Sulphur dioxide and nitrogen oxides','Oxygen','Nitrogen','B'),
('SCI','Grade 7','The nucleus of an atom contains?','Electrons only','Protons and neutrons','Protons only','Neutrons only','B'),
('SCI','Grade 8','The SI unit of force is?','Joule','Newton','Watt','Pascal','B'),
('SCI','Grade 8','Which cell organelle is known as the powerhouse of the cell?','Nucleus','Mitochondria','Ribosome','Golgi body','B'),
('SCI','Grade 8','Which of these is a renewable source of energy?','Coal','Petroleum','Solar energy','Natural gas','C'),
('SCI','Grade 8','The chemical formula of water is?','H2O','CO2','NaCl','O2','A'),
('SCI','Grade 8','Sound cannot travel through?','Air','Water','Vacuum','Solid','C'),
('SCI','Grade 9','The SI unit of work is?','Newton','Joule','Watt','Pascal','B'),
('SCI','Grade 9','The basic structural and functional unit of life is?','Tissue','Cell','Organ','Organism','B'),
('SCI','Grade 9','Which law states that force equals mass times acceleration?','Newton first law','Newton second law','Newton third law','Law of gravitation','B'),
('SCI','Grade 9','Atoms combine to form?','Molecules','Cells','Tissues','Electrons','A'),
('SCI','Grade 9','Separating components of a mixture using their boiling points is called?','Filtration','Distillation','Evaporation','Sublimation','B'),
('SCI','Grade 10','The functional unit of the kidney is called?','Neuron','Nephron','Alveoli','Villi','B'),
('SCI','Grade 10','Which gas is produced when a metal reacts with dilute acid?','Oxygen','Hydrogen','Nitrogen','Carbon dioxide','B'),
('SCI','Grade 10','The process by which DNA copies itself is called?','Transcription','Translation','Replication','Mutation','C'),
('SCI','Grade 10','The power of a lens is measured in?','Meter','Diopter','Watt','Newton','B'),
('SCI','Grade 10','Which of these is a greenhouse gas?','Oxygen','Nitrogen','Carbon dioxide','Hydrogen','C'),
('SCI','Grade 11','The SI unit of electric current is?','Volt','Ampere','Ohm','Watt','B'),
('SCI','Grade 11','Which cell organelle is responsible for protein synthesis?','Mitochondria','Ribosome','Lysosome','Vacuole','B'),
('SCI','Grade 11','The first law of thermodynamics relates to?','Conservation of energy','Conservation of mass','Conservation of momentum','None of these','A'),
('SCI','Grade 11','Which of these is an example of a redox reaction?','Neutralization','Combustion','Precipitation','Dissolution','B'),
('SCI','Grade 11','The value of Avogadro number is approximately?','6.022 x 10^23','3.14 x 10^8','9.8 x 10^2','1.6 x 10^-19','A'),
('SCI','Grade 12','The SI unit of electric charge is?','Ampere','Coulomb','Volt','Farad','B'),
('SCI','Grade 12','DNA replication is termed?','Conservative','Semi-conservative','Dispersive','Random','B'),
('SCI','Grade 12','Which hormone regulates blood sugar level?','Insulin','Thyroxine','Adrenaline','Estrogen','A'),
('SCI','Grade 12','The splitting of white light into its component colors is called?','Reflection','Refraction','Dispersion','Diffraction','C'),
('SCI','Grade 12','In an electrochemical cell, oxidation occurs at the?','Cathode','Anode','Salt bridge','Electrolyte','B'),
-- ===================== SOCIAL SCIENCE =====================
('SST','Grade 6','Who built the Red Fort?','Akbar','Shah Jahan','Aurangzeb','Babur','B'),
('SST','Grade 6','The largest continent in the world is?','Africa','Asia','Europe','Australia','B'),
('SST','Grade 6','India is located mainly in which hemisphere?','Northern','Southern','Eastern only','Western only','A'),
('SST','Grade 6','The Harappan civilization is also known as the?','Vedic civilization','Indus Valley civilization','Gupta civilization','Maurya civilization','B'),
('SST','Grade 6','The head of a village panchayat is called the?','Sarpanch','Mayor','Governor','Collector','A'),
('SST','Grade 7','Who was the founder of the Mughal Empire?','Akbar','Babur','Humayun','Shah Jahan','B'),
('SST','Grade 7','The Tropic of Cancer passes through how many Indian states?','6','7','8','9','C'),
('SST','Grade 7','Which river is known as the Sorrow of Bihar?','Ganga','Kosi','Yamuna','Son','B'),
('SST','Grade 7','The Indian Constitution came into effect on?','15 August 1947','26 January 1950','26 November 1949','2 October 1950','B'),
('SST','Grade 7','Who is known as the Father of the Nation in India?','Jawaharlal Nehru','Mahatma Gandhi','Sardar Patel','B R Ambedkar','B'),
('SST','Grade 8','The Doctrine of Lapse was introduced by?','Lord Curzon','Lord Dalhousie','Lord Wellesley','Lord Cornwallis','B'),
('SST','Grade 8','The longest river in India is?','Yamuna','Godavari','Ganga','Brahmaputra','C'),
('SST','Grade 8','The Indian National Congress was founded in?','1857','1885','1905','1920','B'),
('SST','Grade 8','Which fundamental right guarantees equality before law?','Right to Freedom','Right to Equality','Right to Constitutional Remedies','Right against Exploitation','B'),
('SST','Grade 8','The Vindhya and Satpura ranges are located in?','North India','Central India','South India','East India','B'),
('SST','Grade 9','The French Revolution began in the year?','1776','1789','1804','1815','B'),
('SST','Grade 9','Which type of soil is best suited for cotton cultivation?','Alluvial','Black','Red','Laterite','B'),
('SST','Grade 9','The Preamble of the Indian Constitution declares India as a?','Monarchy','Sovereign Socialist Secular Democratic Republic','Federation only','A colony','B'),
('SST','Grade 9','Which country is considered the origin of democracy?','Rome','Greece','Egypt','India','B'),
('SST','Grade 9','The poverty line in India is estimated mainly based on?','Income','Calorie intake','Literacy','Housing','B'),
('SST','Grade 10','The Non-Cooperation Movement was launched in?','1920','1930','1942','1947','A'),
('SST','Grade 10','Which sector currently contributes the most to India GDP?','Agriculture','Industry','Services','Mining','C'),
('SST','Grade 10','The right to vote for all adult citizens is called?','Universal Adult Franchise','Limited Franchise','Property Franchise','None of these','A'),
('SST','Grade 10','The Deccan Plateau is particularly rich in?','Coal','Minerals','Oil','Water','B'),
('SST','Grade 10','Which power source generates the least pollution?','Coal','Hydropower','Petroleum','Diesel','B'),
('SST','Grade 11','The Indian Ocean lies to the ___ of India.','North','South','East','West','B'),
('SST','Grade 11','Which of these is a feature of democracy?','One-party rule','Free and fair elections','No elections','Hereditary rule','B'),
('SST','Grade 11','The term GDP stands for?','Gross Domestic Product','General Development Plan','Global Development Product','Gross Deficit Percentage','A'),
('SST','Grade 11','The Bhakti movement primarily emphasized?','Caste system','Devotion to God','Military conquest','Trade','B'),
('SST','Grade 11','The smallest state in India by area is?','Sikkim','Goa','Tripura','Kerala','B'),
('SST','Grade 12','The Cold War was primarily between?','India and Pakistan','USA and USSR','UK and France','China and Japan','B'),
('SST','Grade 12','Which five-year plan focused on the Green Revolution?','First','Third','Fifth','Second','B'),
('SST','Grade 12','The term globalization refers to?','Isolation of economies','Integration of world economies','Only trade in goods','None of these','B'),
('SST','Grade 12','Who was the first Prime Minister of independent India?','Sardar Patel','Jawaharlal Nehru','Rajendra Prasad','Lal Bahadur Shastri','B'),
('SST','Grade 12','Panchayati Raj primarily deals with?','Central governance','State governance','Local self-governance','Judicial governance','C'),
-- ===================== ENGLISH =====================
('ENG','Grade 6','Choose the correct synonym of Happy.','Sad','Joyful','Angry','Tired','B'),
('ENG','Grade 6','Identify the noun in: The dog barked loudly.','dog','barked','loudly','The','A'),
('ENG','Grade 6','Choose the correct plural of child.','childs','children','childes','childrens','B'),
('ENG','Grade 6','Which is a verb in: She sings a song.','She','sings','a','song','B'),
('ENG','Grade 6','The opposite of big is?','large','huge','small','tall','C'),
('ENG','Grade 7','Identify the adjective in: The tall boy ran fast.','tall','boy','ran','fast','A'),
('ENG','Grade 7','Choose the correct past tense of go.','goed','gone','went','going','C'),
('ENG','Grade 7','A group of words expressing a complete thought is called a?','Phrase','Sentence','Clause','Paragraph','B'),
('ENG','Grade 7','Choose the correct article: ___ apple a day keeps the doctor away.','A','An','The','No article','B'),
('ENG','Grade 7','Synonym of brave is?','Coward','Fearless','Weak','Timid','B'),
('ENG','Grade 8','Identify the sentence type: What a beautiful day!','Declarative','Interrogative','Exclamatory','Imperative','C'),
('ENG','Grade 8','Choose the correctly spelled word.','Recieve','Receive','Receeve','Receve','B'),
('ENG','Grade 8','Which is a preposition in: The book is on the table.','book','is','on','table','C'),
('ENG','Grade 8','The passive voice of She writes a letter is?','A letter is written by her','A letter writes her','She is written a letter','A letter was written by her','A'),
('ENG','Grade 8','Antonym of ancient is?','old','modern','historic','traditional','B'),
('ENG','Grade 9','Identify the figure of speech in: The stars danced in the sky.','Simile','Personification','Metaphor','Alliteration','B'),
('ENG','Grade 9','Choose the correct conditional sentence.','If it rains, I would stay home','If it rains, I will stay home','If it rain, I will stay home','If it will rain, I stay home','B'),
('ENG','Grade 9','A word that describes a noun is called a?','Verb','Adverb','Adjective','Conjunction','C'),
('ENG','Grade 9','Choose the correct indirect speech for: He said, I am tired.','He said that he was tired','He said that I am tired','He said that he is tired','He said I was tired','A'),
('ENG','Grade 9','Synonym of enormous is?','Tiny','Huge','Narrow','Short','B'),
('ENG','Grade 10','Identify the clause type in: Although it rained, we went out.','Main clause','Subordinate clause','Independent clause','None of these','B'),
('ENG','Grade 10','Which sentence uses the apostrophe correctly to mean it is raining?','Its raining','It''s raining','Its'' raining','It is'' raining','B'),
('ENG','Grade 10','A poem with 14 lines is called a?','Ode','Sonnet','Ballad','Elegy','B'),
('ENG','Grade 10','Identify the grammatically correct sentence.','Neither of the boys were present','Neither of the boys was present','Neither of the boy was present','Neither of boys was present','B'),
('ENG','Grade 10','The literary device of deliberate exaggeration is called?','Hyperbole','Metaphor','Simile','Irony','A'),
('ENG','Grade 11','The tone of a sarcastic remark is best described as?','Serious','Mocking','Sad','Neutral','B'),
('ENG','Grade 11','Choose the correct form: She has been ___ for two hours.','study','studying','studied','studies','B'),
('ENG','Grade 11','A narrative told from the I perspective is written in?','Third person','First person','Second person','Omniscient','B'),
('ENG','Grade 11','An oxymoron combines?','Similar words','Contradictory terms','Rhyming words','Repeated sounds','B'),
('ENG','Grade 11','The main idea of a passage is called its?','Theme','Setting','Plot','Climax','A'),
('ENG','Grade 12','A soliloquy in drama is spoken?','To another character','To the audience or self, alone','In a group','Never aloud','B'),
('ENG','Grade 12','Choose the correct use of the subjunctive mood.','If I was rich, I would travel','If I were rich, I would travel','If I am rich, I would travel','If I will be rich, I travel','B'),
('ENG','Grade 12','Stream of consciousness is a narrative technique that shows?','A character continuous flow of thoughts','Historical facts','Dialogue only','Scene descriptions','A'),
('ENG','Grade 12','An epic is typically characterized by?','Short length','A heroic narrative on a grand scale','Comedy','Non-fiction','B'),
('ENG','Grade 12','The term protagonist refers to?','The villain','The main character','The narrator only','A minor character','B'),
-- ===================== HINDI =====================
('HIN','Grade 6','Pustak (book) belongs to which part of speech in Hindi grammar?','Sangya (Noun)','Sarvanam (Pronoun)','Kriya (Verb)','Visheshan (Adjective)','A'),
('HIN','Grade 6','The Hindi word for friend is?','Mitra','Shatru','Guru','Chatra','A'),
('HIN','Grade 6','Which of these is a Hindi vowel (swar)?','Ka','A','Ta','Pa','B'),
('HIN','Grade 6','The plural of ladka (boy) is?','Ladke','Ladka','Ladkon','Ladkiyaan','A'),
('HIN','Grade 6','Tum (you) is an example of?','Sarvanam (Pronoun)','Sangya (Noun)','Kriya (Verb)','Avyaya (Indeclinable)','A'),
('HIN','Grade 7','Main ne khaana khaaya identifies which tense?','Present','Past','Future','None of these','B'),
('HIN','Grade 7','Antonym of din (day) is?','Raat (night)','Subah (morning)','Shaam (evening)','Samay (time)','A'),
('HIN','Grade 7','Which of these is an example of a compound word (samas)?','Ramayan','Ghar','Ped','Phool','A'),
('HIN','Grade 7','Sundar (beautiful) is an example of a?','Sangya','Visheshan (Adjective)','Kriya','Sarvanam','B'),
('HIN','Grade 7','The feminine form of ladka is?','Ladki','Ladke','Balak','Yuvak','A'),
('HIN','Grade 8','Muhaavara means?','Idiom','Poem','Story','Essay','A'),
('HIN','Grade 8','The correct sandhi of vidya + aalay is?','Vidyalaya','Vidyalaay','Vidyaaalay','Vidyalay','A'),
('HIN','Grade 8','Karta is an example of which grammatical case (karak)?','Nominative case','Rang (color)','Sankhya (number)','Kaal (tense)','A'),
('HIN','Grade 8','In Ram ne Ravan ko maara, the karta (subject) is?','Ram','Ravan','Maara','Ko','A'),
('HIN','Grade 8','Hindi is written in which script?','Roman','Devanagari','Gurmukhi','Urdu','B'),
('HIN','Grade 9','Alankar in Hindi literature refers to?','Figures of speech','Grammar rules','Punctuation','Vocabulary','A'),
('HIN','Grade 9','Which of these is an example of an upsarga (prefix)?','Pra (in prayog)','Ee (in sundari)','Ta (in sundarta)','Pan (in bachpan)','A'),
('HIN','Grade 9','Ras in Hindi poetry refers to?','Emotion or sentiment','Rhyme','Meter','Syllable','A'),
('HIN','Grade 9','The correct vilom (antonym) of aasha (hope) is?','Niraasha (despair)','Khushi (happiness)','Prem (love)','Ghrina (hatred)','A'),
('HIN','Grade 9','Kriya refers to which part of speech?','Verb','Noun','Adjective','Pronoun','A'),
('HIN','Grade 10','Chhand in Hindi poetry refers to?','A meter or verse form','A story','Grammar','Script','A'),
('HIN','Grade 10','Which of these is an example of a tatsam word (borrowed directly from Sanskrit)?','Agni','Aag','Paani','Chaand','A'),
('HIN','Grade 10','Samas means?','Compound word','Sentence','Paragraph','Idiom','A'),
('HIN','Grade 10','The karak vibhakti used for the object (karm) is?','Ko','Se','Ka','Mein','A'),
('HIN','Grade 10','Muktak kaavya refers to?','Independent verses not part of a larger story','Epic poetry','Drama','Prose','A'),
('HIN','Grade 11','Gadya refers to?','Prose','Poetry','Drama','Verse','A'),
('HIN','Grade 11','Who is known as the father of modern Hindi literature?','Bharatendu Harishchandra','Tulsidas','Kabir','Munshi Premchand','A'),
('HIN','Grade 11','Chhayavaad is a movement in Hindi?','Poetry','Drama','Grammar','Journalism','A'),
('HIN','Grade 11','Munshi Premchand is famous for writing?','Novels and short stories','Devotional poetry','Grammar textbooks','Plays only','A'),
('HIN','Grade 11','Nibandh means?','Essay','Poem','Novel','Drama','A'),
('HIN','Grade 12','Upanyaas means?','Novel','Short story','Poem','Essay','A'),
('HIN','Grade 12','Kabir poetry primarily belongs to which stream?','Nirgun Bhakti','Sagun Bhakti','Reetikal','Adhunik Kal','A'),
('HIN','Grade 12','Naatak refers to?','Drama','Novel','Essay','Poem','A'),
('HIN','Grade 12','Jaishankar Prasad is associated with which literary movement?','Chhayavaad','Reetikal','Bhaktikal','Aadikal','A'),
('HIN','Grade 12','Aalochana means?','Criticism','Praise','Narration','Translation','A'),
-- ===================== SANSKRIT =====================
('SAN','Grade 6','The Sanskrit word for water is?','Jal','Agni','Vayu','Prithvi','A'),
('SAN','Grade 6','Namah is used to express?','Greeting or salutation','Anger','A question','A command','A'),
('SAN','Grade 6','The Sanskrit word for teacher is?','Shishya','Guru','Mitra','Raja','B'),
('SAN','Grade 6','Sanskrit is written in which script?','Devanagari','Roman','Gurmukhi','Tamil','A'),
('SAN','Grade 6','The Sanskrit word for book is?','Pustakam','Vahanam','Griham','Vrikshah','A'),
('SAN','Grade 7','The Sanskrit word aham means?','You','I','He','She','B'),
('SAN','Grade 7','Gacchati is a verb form meaning?','He or she goes','He or she eats','He or she reads','He or she sleeps','A'),
('SAN','Grade 7','The Sanskrit term for sun is?','Suryah','Chandrah','Taarah','Prithvi','A'),
('SAN','Grade 7','Dhanyavadah means?','Sorry','Thank you','Hello','Goodbye','B'),
('SAN','Grade 7','The Sanskrit numeral for five is?','Pancha','Chatur','Shat','Tri','A'),
('SAN','Grade 8','In Sanskrit grammar, sandhi refers to?','Joining of sounds or words','A type of verb','A type of noun','Punctuation','A'),
('SAN','Grade 8','Vidyalayah means?','School','Home','Temple','Market','A'),
('SAN','Grade 8','The three genders in Sanskrit grammar are?','Pulling, Streeling and Napunsakling','Only masculine and feminine','Only neuter','None of these','A'),
('SAN','Grade 8','In Krishnah vanam gacchati, the subject (karta) is?','Krishnah','Vanam','Gacchati','None of these','A'),
('SAN','Grade 8','The Sanskrit word for friend is?','Mitram','Shatru','Guru','Raja','A'),
('SAN','Grade 9','Vibhakti in Sanskrit grammar refers to?','Case endings','Verb tenses','Gender','Number','A'),
('SAN','Grade 9','How many vibhaktis (cases) are there in Sanskrit?','Six','Seven','Eight','Five','C'),
('SAN','Grade 9','Dhatu in Sanskrit grammar means?','Verb root','Noun','Adjective','Pronoun','A'),
('SAN','Grade 9','The Sanskrit term for present tense is?','Lat lakara','Lit lakara','Lrit lakara','Lot lakara','A'),
('SAN','Grade 9','In Ramah pustakam pathati, the object (karma) is?','Ramah','Pustakam','Pathati','None of these','B'),
('SAN','Grade 10','Samasa in Sanskrit means?','Compound word','Sentence','Simple word','Root word','A'),
('SAN','Grade 10','Which lakara (tense) denotes future action?','Lat','Lrit','Lang','Vidhiling','B'),
('SAN','Grade 10','Asti means?','Is or exists','Was','Will be','Has been','A'),
('SAN','Grade 10','The Sanskrit term for a shloka meter is?','Chhandas','Sandhi','Samasa','Karaka','A'),
('SAN','Grade 10','Guruh shishyam paathayati means?','The teacher teaches the student','The student teaches the teacher','The teacher reads a book','The student reads a book','A'),
('SAN','Grade 11','Kalidasa is a great poet in which language?','Sanskrit','Hindi','Tamil','Pali','A'),
('SAN','Grade 11','Abhijnanashakuntalam is a famous work by?','Kalidasa','Tulsidas','Valmiki','Vyasa','A'),
('SAN','Grade 11','The Sanskrit epic Ramayana was composed by?','Valmiki','Vyasa','Kalidasa','Bhavabhuti','A'),
('SAN','Grade 11','The Mahabharata was composed by?','Ved Vyasa','Valmiki','Kalidasa','Panini','A'),
('SAN','Grade 11','Panini is famous for his work on?','Sanskrit grammar','Sanskrit poetry','Sanskrit drama','Sanskrit philosophy','A'),
('SAN','Grade 12','The Ashtadhyayi is a treatise on?','Sanskrit grammar','Astronomy','Mathematics','Medicine','A'),
('SAN','Grade 12','Which Sanskrit text is considered the oldest of the Vedas?','Rigveda','Yajurveda','Samaveda','Atharvaveda','A'),
('SAN','Grade 12','Kavya in Sanskrit literature refers to?','Poetic composition','Drama only','Grammar','Philosophy','A'),
('SAN','Grade 12','Bhavabhuti was a renowned Sanskrit?','Playwright','Grammarian','Mathematician','Astronomer','A'),
('SAN','Grade 12','The Upanishads primarily deal with?','Philosophical and spiritual knowledge','Grammar','Poetry','Drama','A'),
-- ===================== COMPUTER SCIENCE =====================
('CS','Grade 6','A computer main memory is called?','RAM','CPU','Hard disk','Monitor','A'),
('CS','Grade 6','Which of these is an input device?','Monitor','Printer','Keyboard','Speaker','C'),
('CS','Grade 6','The full form of CPU is?','Central Processing Unit','Computer Personal Unit','Central Program Unit','Control Processing Unit','A'),
('CS','Grade 6','MS Word is an example of?','Operating System','Application software','Hardware','Input device','B'),
('CS','Grade 6','Which of these is an output device?','Mouse','Keyboard','Monitor','Scanner','C'),
('CS','Grade 7','A collection of related data organized for easy access is called a?','Program','Database','Network','Algorithm','B'),
('CS','Grade 7','Which of these is a programming language?','Windows','Python','MS Excel','Photoshop','B'),
('CS','Grade 7','The internet is an example of a?','LAN','WAN','PAN','MAN','B'),
('CS','Grade 7','Which key deletes a character to the left of the cursor?','Delete','Backspace','Enter','Shift','B'),
('CS','Grade 7','A set of instructions to perform a task is called?','Data','Algorithm','Hardware','Network','B'),
('CS','Grade 8','HTML stands for?','Hyper Text Markup Language','High Text Machine Language','Hyperlink Text Markup Language','Home Tool Markup Language','A'),
('CS','Grade 8','Which of these is an example of an operating system?','MS Word','Windows','Photoshop','Chrome','B'),
('CS','Grade 8','The binary number system uses which digits?','0 and 1','0 to 9','1 to 9','A to F','A'),
('CS','Grade 8','A variable in programming is used to?','Store data','Display images','Print documents','Connect to internet','A'),
('CS','Grade 8','Which of these is a web browser?','Excel','Chrome','Word','Paint','B'),
('CS','Grade 9','A loop in programming is used to?','Store data once','Repeat a set of instructions','Delete data','Connect to internet','B'),
('CS','Grade 9','The full form of URL is?','Uniform Resource Locator','Universal Resource Link','Unique Resource Locator','United Resource Locator','A'),
('CS','Grade 9','Which of these is a valid Python data type?','int','integer','num','numeric','A'),
('CS','Grade 9','An IDE is used for?','Writing and running code','Browsing the internet','Editing images','Playing music','A'),
('CS','Grade 9','A conditional statement in programming is used to?','Repeat code','Make decisions','Store data','Delete files','B'),
('CS','Grade 10','SQL is primarily used for?','Managing databases','Designing web pages','Writing operating systems','Image editing','A'),
('CS','Grade 10','A function in programming is a?','Block of reusable code','A type of variable','A type of loop','A hardware component','A'),
('CS','Grade 10','Which of these best describes an array?','A single number','A collection of elements of the same type','A single string','A function','B'),
('CS','Grade 10','The full form of CSS is?','Cascading Style Sheets','Computer Style Sheets','Creative Style Sheets','Colorful Style Sheets','A'),
('CS','Grade 10','Cyber security primarily deals with protecting?','Hardware only','Data and systems from attacks','Only networks','Only software','B'),
('CS','Grade 11','An object in object-oriented programming is an instance of a?','Function','Class','Variable','Loop','B'),
('CS','Grade 11','Which of these is a NoSQL database?','MySQL','MongoDB','PostgreSQL','Oracle','B'),
('CS','Grade 11','Recursion in programming refers to a function that?','Calls itself','Never returns','Has no parameters','Runs only once','A'),
('CS','Grade 11','The time complexity of binary search is?','O(n)','O(log n)','O(n squared)','O(1)','B'),
('CS','Grade 11','Encapsulation in OOP refers to?','Hiding internal details of an object','Creating multiple objects','Inheriting properties','None of these','A'),
('CS','Grade 12','Inheritance in OOP allows a class to?','Acquire properties of another class','Delete another class','Duplicate itself','None of these','A'),
('CS','Grade 12','Which sorting algorithm has the best average case time complexity?','Bubble sort','Merge sort','Selection sort','Insertion sort','B'),
('CS','Grade 12','Normalization in databases is used to?','Increase redundancy','Reduce data redundancy','Delete data','Encrypt data','B'),
('CS','Grade 12','A stack data structure follows which principle?','FIFO','LIFO','Random access','Priority','B'),
('CS','Grade 12','Polymorphism in OOP means?','One interface, multiple implementations','Multiple interfaces, one implementation','No interface','None of these','A'),
-- ===================== PHYSICAL EDUCATION =====================
('PE','Grade 6','How many players are there in a football team on the field?','9','10','11','12','C'),
('PE','Grade 6','Which exercise improves flexibility?','Weightlifting','Stretching','Sprinting','None of these','B'),
('PE','Grade 6','The Olympic Games are held every?','2 years','4 years','5 years','3 years','B'),
('PE','Grade 6','A balanced diet includes?','Only proteins','Only carbohydrates','All nutrients in the right proportion','Only fats','C'),
('PE','Grade 6','Which sport uses a shuttlecock?','Tennis','Badminton','Cricket','Hockey','B'),
('PE','Grade 7','How many players are on a basketball team on the court?','5','6','7','11','A'),
('PE','Grade 7','Warm-up exercises before a game help to?','Cause injury','Prevent injury','Increase weight','None of these','B'),
('PE','Grade 7','The game of cricket originated in?','India','England','Australia','USA','B'),
('PE','Grade 7','Which vitamin is obtained mainly from sunlight?','Vitamin A','Vitamin C','Vitamin D','Vitamin K','C'),
('PE','Grade 7','A foul in basketball refers to?','Illegal physical contact','Scoring a goal','A timeout','A substitution','A'),
('PE','Grade 8','The term deuce is used in which sport?','Football','Tennis','Cricket','Hockey','B'),
('PE','Grade 8','Which organ improves its capacity through aerobic exercise?','Liver','Heart and lungs','Kidney','Stomach','B'),
('PE','Grade 8','How many players are on a volleyball team on court?','5','6','7','11','B'),
('PE','Grade 8','The yorker is a term used in?','Cricket','Football','Hockey','Tennis','A'),
('PE','Grade 8','Which of these is an example of anaerobic exercise?','Jogging','Sprinting','Swimming laps','Long-distance cycling','B'),
('PE','Grade 9','The term love (zero score) is used in?','Cricket','Tennis','Football','Hockey','B'),
('PE','Grade 9','A balanced diet should include carbohydrates, proteins, fats, vitamins, minerals and?','Sugar only','Water','Salt only','None of these','B'),
('PE','Grade 9','Which of these is a team sport?','Chess','Swimming','Hockey','Boxing','C'),
('PE','Grade 9','The offside rule is associated with?','Football','Cricket','Badminton','Table tennis','A'),
('PE','Grade 9','BMI stands for?','Body Mass Index','Basic Muscle Index','Body Movement Index','Basic Mass Indicator','A'),
('PE','Grade 10','Which sport is famously played at Wimbledon?','Tennis','Cricket','Golf','Football','A'),
('PE','Grade 10','The number of players in a kabaddi team on court is?','5','7','9','11','B'),
('PE','Grade 10','Slam dunk is a term from which sport?','Basketball','Volleyball','Football','Hockey','A'),
('PE','Grade 10','Which nutrient is the primary source of energy?','Protein','Carbohydrate','Vitamin','Mineral','B'),
('PE','Grade 10','Which Olympic event measures the fastest human sprint?','Marathon','100m dash','Long jump','High jump','B'),
('PE','Grade 11','The governing body of world football is?','FIFA','IOC','BCCI','ICC','A'),
('PE','Grade 11','Cardiovascular endurance is best improved by?','Weightlifting','Aerobic exercises','Stretching only','Rest','B'),
('PE','Grade 11','The term ace in tennis refers to?','A serve the opponent fails to return','A foul','A timeout','A substitution','A'),
('PE','Grade 11','Which of these best prevents muscle injury?','Skipping warm-up','Proper warm-up and cool-down','Overtraining','Ignoring pain','B'),
('PE','Grade 11','The governing body of the Olympics is?','FIFA','IOC','ICC','WHO','B'),
('PE','Grade 12','VO2 max measures?','Muscle strength','Maximum oxygen consumption during exercise','Flexibility','Reaction time','B'),
('PE','Grade 12','Which training method improves speed and power together?','Plyometrics','Static stretching','Yoga','Meditation','A'),
('PE','Grade 12','Periodization in sports training refers to?','Random training','Structured phases of training over time','One-time training','No training plan','B'),
('PE','Grade 12','BCCI is the governing body for which sport in India?','Football','Cricket','Hockey','Badminton','B'),
('PE','Grade 12','Overtraining syndrome can lead to?','Improved performance','Fatigue and decreased performance','No effect','Immediate strength gain','B')
) AS v(subject_code, class_name, question_text, option_a, option_b, option_c, option_d, correct_option)
JOIN subject sub ON sub.code = v.subject_code AND sub.school_id = '99999999-9999-9999-9999-999999999999';
